### ISSUE TITLE
Recreating existing queue will fail if configuration settings have changed 

### ISSUE THREAD

**Issue by sphuber** [aiidateam/kiwipy#60]
I came across this when I was running of `0.6.0` in my dev environment. Note that at this point we haven't yet migrated `plumpy` nor `aiida-core` to `asyncio`. When I launched a process, I was faced with the following exception:
```
Traceback (most recent call last):
  File "/home/sph/.virtualenvs/aiida_dev/lib/python3.7/site-packages/aiormq/base.py", line 25, in __inner
    return await self.task
concurrent.futures._base.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/sph/code/aiida/env/dev/kiwipy/kiwipy/rmq/communicator.py", line 470, in task_send
    task_queue = await self.get_default_task_queue()
  File "/home/sph/code/aiida/env/dev/kiwipy/kiwipy/rmq/communicator.py", line 353, in get_default_task_queue
    await task_queue.connect()
  File "/home/sph/code/aiida/env/dev/kiwipy/kiwipy/rmq/tasks.py", line 424, in connect
    await self._subscriber.connect()
  File "/home/sph/code/aiida/env/dev/kiwipy/kiwipy/rmq/tasks.py", line 94, in connect
    await self._create_task_queue()
  File "/home/sph/code/aiida/env/dev/kiwipy/kiwipy/rmq/tasks.py", line 143, in _create_task_queue
    arguments=arguments)
  File "/home/sph/.virtualenvs/aiida_dev/lib/python3.7/site-packages/aio_pika/robust_channel.py", line 173, in declare_queue
    timeout=timeout,
  File "/home/sph/.virtualenvs/aiida_dev/lib/python3.7/site-packages/aio_pika/channel.py", line 303, in declare_queue
    await queue.declare(timeout=timeout)
  File "/home/sph/.virtualenvs/aiida_dev/lib/python3.7/site-packages/aio_pika/queue.py", line 101, in declare
    timeout=timeout,
  File "/usr/lib/python3.7/asyncio/tasks.py", line 414, in wait_for
    return await fut
  File "/home/sph/.virtualenvs/aiida_dev/lib/python3.7/site-packages/aiormq/channel.py", line 641, in queue_declare
    arguments=arguments,
  File "/home/sph/.virtualenvs/aiida_dev/lib/python3.7/site-packages/aiormq/base.py", line 168, in wrap
    return await self.create_task(func(self, *args, **kwargs))
  File "/home/sph/.virtualenvs/aiida_dev/lib/python3.7/site-packages/aiormq/base.py", line 27, in __inner
    raise self.exception from e
  File "/usr/lib/python3.7/asyncio/tasks.py", line 630, in _wrap_awaitable
    return (yield from awaitable.__await__())
  File "/home/sph/.virtualenvs/aiida_dev/lib/python3.7/site-packages/aiormq/base.py", line 27, in __inner
    raise self.exception from e
aiormq.exceptions.ChannelPreconditionFailed: PRECONDITION_FAILED - inequivalent arg 'x-message-ttl' for queue 'aiida-ba564ed1231947c88e650f56b0ef5ef6.process.queue' in vhost '/': received '72576000000' but current is '604800000'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./launch_arithmetic_add.py", line 61, in <module>
    launch()
  File "/home/sph/.virtualenvs/aiida_dev/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/sph/.virtualenvs/aiida_dev/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/sph/.virtualenvs/aiida_dev/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/sph/.virtualenvs/aiida_dev/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/sph/code/aiida/env/dev/aiida-core/aiida/cmdline/utils/decorators.py", line 65, in wrapper
    return wrapped(*args, **kwargs)
  File "./launch_arithmetic_add.py", line 48, in launch
    node = launch.submit(ArithmeticAddCalculation, **inputs)
  File "/home/sph/code/aiida/env/dev/aiida-core/aiida/engine/launch.py", line 124, in submit
    controller.continue_process(process.pid, nowait=False, no_reply=True)
  File "/home/sph/.virtualenvs/aiida_dev/lib/python3.7/site-packages/plumpy/process_comms.py", line 371, in continue_process
    return self.task_send(message, no_reply=no_reply)
  File "/home/sph/.virtualenvs/aiida_dev/lib/python3.7/site-packages/plumpy/process_comms.py", line 441, in task_send
    return self._communicator.task_send(message, no_reply=no_reply)
  File "/home/sph/code/aiida/env/dev/kiwipy/kiwipy/rmq/threadcomms.py", line 193, in task_send
    return self._loop_scheduler.await_(self._communicator.task_send(task, no_reply))
  File "/home/sph/.virtualenvs/aiida_dev/lib/python3.7/site-packages/pytray/aiothreads.py", line 155, in await_
    return self.await_submit(awaitable).result(timeout=self.task_timeout)
  File "/usr/lib/python3.7/concurrent/futures/_base.py", line 435, in result
    return self.__get_result()
  File "/usr/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/home/sph/.virtualenvs/aiida_dev/lib/python3.7/site-packages/pytray/aiothreads.py", line 35, in done
    result = done_future.result()
  File "/home/sph/.virtualenvs/aiida_dev/lib/python3.7/site-packages/pytray/aiothreads.py", line 169, in proxy
    return await awaitable
  File "/home/sph/code/aiida/env/dev/kiwipy/kiwipy/rmq/communicator.py", line 477, in task_send
    raise kiwipy.TaskRejected(str(exception))
kiwipy.exceptions.TaskRejected: PRECONDITION_FAILED - inequivalent arg 'x-message-ttl' for queue 'aiida-ba564ed1231947c88e650f56b0ef5ef6.process.queue' in vhost '/': received '72576000000' but current is '604800000'
```
This is because we changed the message TTL for the task queue in `0.5.4` which was also included in `0.6.0`. Apparently `aiormq` doesn't take too kindly to us changing the configuration of existing queues. This will of course be a big problem once this hits the users of `aiida-core` because the task queues are long lived and there is no API to delete them nor a way to reset the message TTL. This will break their installations completely. Bad news bears.

The weird thing is, is that I tried to reproduce this with `0.5.4` but there I am not seeing the problem. I actually remember dealing with this problem of changing queue parameters a long time ago, so I think what must have happened is that some switch we put in back then that allows changing live queue parameters, got lost in the `asyncio` migration. I will go through the history to try and find it. @muhrin do you recall when this was or where this might have been set?

**Comment by sphuber** [comment]
Fixed in PR #63

**Comment by zhubonan** [comment]
BTW Is there any plan to update this value in the future? 
When a user migrates to a newer version of AiiDA, usually there should not be any running processes. If that is the case, it should be just a matter of deleting and recreating the queue?

**Comment by sphuber** [comment]
No concrete plans, but I can tell you the limitations that we are facing. Yes it is possible to change the setting value if we destroy the queue and then have it be recreated. The recreation would be automatic, so that is the easy part. However, the difficult part is destroying the existing queue. This is only possible through the `rabbitmqctl` tool, which requires sudo rights. Normally the migration to a new AiiDA version is fully automatic, and typically just requires running the database migrations. Here we would have to add a "RabbitMQ" migration, that deletes the queue. If this was possible through Python, we could add something, but the fact that we would have to perform a system call with sudo rights, makes this very fragile and unlikely to be automatable. Telling users that they have to execute certain commands manually will not be very user friendly. If we can come up with a robust and automated way to delete the relevant queues of a specific profile, then that would be great and we can change these values.

**Comment by zhubonan** [comment]
I see. I agree that asking for `sudo` is not good and fragile. For me, this would not work as the RabbitMQ is installed on the windows side and AiiDA is inside WSL. 

Rather than destroying the queue, would it be possible just to simply subscribe to a new queue and leave the old one along? My understanding is that the queue name is based on some hash related to the profile name, configuration file paths etc. Perhaps in the migration we just change how to hash is computed (add hash salt) so a different queue is used. The *salt* can be related to the TTL values, so if the user wants to change the TTL later it is also possible.

**Comment by sphuber** [comment]
That's a good idea. For now the queue name is simply based on the profile UUID. So something like `aiida-<PROFILE_UUID>-process-queue`. Not that there are more queues, but this is the one that is relevant for the issue of the TTL of process tasks. We could indeed see if we can make the name rather based on a hash of profile_uuid + important queue settings.
